# Generated by Django 4.0 on 2024-03-05 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import guia_db.models.ArtworkImage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('art_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('artist_name', models.TextField()),
                ('medium', models.TextField()),
                ('date_published', models.TextField()),
                ('dimen_width_cm', models.DecimalField(decimal_places=2, max_digits=100)),
                ('dimen_length_cm', models.DecimalField(decimal_places=2, max_digits=100)),
                ('dimen_height_cm', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('description', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guia_db.admin', verbose_name='added by')),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('museum_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('museum_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only letters, digits, hyphen, and underscore', regex='^[a-zA-Z0-9_-]*$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visitor_token', models.TextField(editable=False)),
                ('visited_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_name', models.TextField()),
                ('museum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_db.museum', verbose_name='museum_id')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkVisits',
            fields=[
                ('visit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('art_visited_on', models.DateTimeField(auto_now_add=True)),
                ('visit_type', models.CharField(choices=[('scan', 'Scan'), ('manual', 'Manual')], default='manual', max_length=6)),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_db.artwork', verbose_name='art_id')),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_db.visitor', verbose_name='visitor_id')),
            ],
            options={
                'verbose_name_plural': 'Artwork Visits',
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=guia_db.models.ArtworkImage.get_upload_to)),
                ('image_link', models.TextField(blank=True)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guia_db.artwork')),
            ],
            options={
                'verbose_name_plural': 'Artwork Images',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_artworks', to='guia_db.section', verbose_name='section_id'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_artworks', to='guia_db.admin', verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='admin',
            name='museum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_db.museum', verbose_name='museum id'),
        ),
    ]
