# Generated by Django 4.0 on 2024-03-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='museum_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guia_db.museum', verbose_name='museum_id'),
        ),
    ]
