# Generated by Django 5.0.1 on 2024-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('museum_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('museum_name', models.TextField()),
            ],
        ),
    ]
