# Generated by Django 5.0.1 on 2024-01-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0002_museum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Museum',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
