# Generated by Django 5.0.1 on 2024-01-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia_db', '0003_delete_admin_delete_museum_delete_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('museum_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('museum_name', models.TextField()),
            ],
        ),
    ]
