# Generated by Django 4.0 on 2024-04-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0004_alter_artwork_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkvisits',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artworkvisits',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
