# Generated by Django 5.0.1 on 2024-02-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visitor_token', models.TextField(editable=False)),
                ('visited_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
