# Generated by Django 5.0.1 on 2024-02-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0008_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork_Visits',
            fields=[
                ('visit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('art_visited_on', models.DateTimeField(auto_now_add=True)),
                ('visit_type', models.CharField(choices=[('scan', 'Scan'), ('manual', 'Manual')], default='manual', max_length=6)),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_db.artwork', verbose_name='art_id')),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_db.visitor', verbose_name='visitor_id')),
            ],
        ),
    ]
