# Generated by Django 4.0 on 2024-02-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0011_user_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(max_length=128),
        ),
    ]
