# Generated by Django 4.0 on 2024-02-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0013_alter_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='admin_username',
        ),
    ]
