# Generated by Django 4.0 on 2024-02-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0017_artwork_images_delete_artworkimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='images',
        ),
        migrations.CreateModel(
            name='ArtworkImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artwork/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guia_db.artwork')),
            ],
        ),
    ]
