# Generated by Django 4.0 on 2024-02-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0018_remove_artwork_images_artworkimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='images',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ArtworkImages',
        ),
    ]
