# Generated by Django 4.0 on 2024-02-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0019_artwork_images_delete_artworkimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='images',
        ),
    ]
