# Generated by Django 4.0 on 2024-02-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0021_artworkimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkimage',
            options={'verbose_name_plural': 'Artwork Images'},
        ),
    ]
