# Generated by Django 4.0 on 2024-02-14 07:06

from django.db import migrations, models
import guia_db.models.ArtworkImage


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0022_alter_artworkimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(upload_to=guia_db.models.ArtworkImage.get_upload_to),
        ),
    ]
