# Generated by Django 4.0 on 2024-02-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0023_alter_artworkimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkimage',
            name='isThumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
