# Generated by Django 4.0 on 2024-02-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0024_artworkimage_isthumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworkimage',
            old_name='isThumbnail',
            new_name='is_thumbnail',
        ),
    ]
