# Generated by Django 4.0 on 2024-02-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0025_rename_isthumbnail_artworkimage_is_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_name',
            field=models.TextField(default=''),
        ),
    ]
