# Generated by Django 4.0 on 2024-02-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0026_artwork_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist_name',
            field=models.TextField(),
        ),
    ]
