# Generated by Django 4.0 on 2024-02-20 08:16

from django.db import migrations, models
import guia_db.models.ArtworkImage


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0027_alter_artwork_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkimage',
            name='image_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=guia_db.models.ArtworkImage.get_upload_to),
        ),
    ]
