# Generated by Django 4.0 on 2024-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_db', '0028_artworkimage_image_link_alter_artworkimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
